name: Build and Push Docker Image for Main

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.NFS3BRIDGE_ACTIONS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Define Tags
        id: prep
        run: |
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
          echo "TAGS=ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:$SHA_SHORT" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
